### ISSUE TITLE
Año 2017

### ISSUE THREAD

**Issue by Nullpo** [scoffey/elegilegi#4]
Buenas tardes!

Tienen pensado reflotar este proyecto, para las elecciones de este año?

**Comment by martinszy** [comment]
Para hacerlo se necesitaría:
1) Seleccionar los 20 proyectos más importantes de los últimos 2 años. Preferentemente que lo haga un politólogo muy informado y sin sesgo partidario.
2) Información de cómo se votó cada uno de esos proyectos, que se puede sacar de los fusion tables de decadavotada de andy tow o directamente de los CSV de votaciones.hdcn.gob.ar 
3) Un ratito de codeo para meter todo eso en el juego
4) Deploy. No sé si está disponible el dominio y el servidor donde se hosteó esto en 2013, sino puedo ofrecer yo.

**Comment by Nullpo** [comment]
Si consiguen el 1, me prendo en el 2, 3, y 4. Y el dominio esta disponible en nic.ar :)

**Comment by martinszy** [comment]
Parece que conseguimos el 1, andá preparando lo demás, si quieren hacemos una llamadita para coordinar.

**Comment by Nullpo** [comment]
Dale! En esta semana me bajo el codigo, lo chusmeo, y coordinamos.

**Comment by martinszy** [comment]
Algún avance?

**Comment by martinszy** [comment]
Che, ya está: http://elegilegi.com.ar/
Lo hizo @scoffey sin avisar parece.

**Comment by scoffey** [comment]
Lo avisé en Twitter. Cualquier cosa me pueden contactar por ahí. Gracias!

Cierro ya que la edición 2017 ya está implementada.
